# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Checkout code from repository
- checkout: self

# Install Terraform
- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: latest

# Terraform Init
- script: |
    terraform init
  displayName: Terraform Init

# Terraform Validate
- script: |
    terraform validate
  displayName: Terraform Validate

# Terraform Plan
- script: |
    terraform plan -out=tfplan
  displayName: Terraform Plan

# Terraform Apply
- script: |
    terraform apply -auto-approve tfplan
  displayName: Terraform Apply
