trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- script: terraform version
  displayName: Terraform Version

- script: terraform init
  displayName: Terraform Init
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform

- script: terraform validate
  displayName: Terraform Validate
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform

- script: terraform plan -out=tfplan
  displayName: Terraform Plan
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform

- script: terraform apply -auto-approve tfplan
  displayName: Terraform Apply
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform
