trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

# Check existing Terraform
- script: |
    terraform version
  displayName: Check Terraform Version

# Terraform Init
- script: |
    terraform init
  displayName: Terraform Init

# Terraform Validate
- script: |
    terraform validate
  displayName: Terraform Validate

# Terraform Plan
- script: |
    terraform plan -out=tfplan
  displayName: Terraform Plan

# Terraform Apply
- script: |
    terraform apply -auto-approve tfplan
  displayName: Terraform Apply